import { Order, Product} from './types';

const products: Product[] = [
    {
        id: 1,
        name: '2500 Club Coupe',
        category: 'GMC',
        image: 'https://robohash.org/optioanimiullam.png?size=100x100&set=set1',
        added_date: '2/17/2019',
        rating: 3,
        price: 451.05,
        quantity: 157,
        status: true,
    },
    {
        id: 2,
        name: '8 Series',
        category: 'BMW',
        image: 'https://robohash.org/doloribusatconsequatur.png?size=100x100&set=set1',
        added_date: '6/12/2019',
        rating: 2,
        price: 419.5,
        quantity: 246,
        status: true,
    },
    {
        id: 3,
        name: 'Sigma',
        category: 'Mitsubishi',
        image: 'https://robohash.org/animidebitisfacilis.png?size=100x100&set=set1',
        added_date: '1/7/2019',
        rating: 2,
        price: 355.86,
        quantity: 376,
        status: true,
    },
    {
        id: 4,
        name: '600SL',
        category: 'Mercedes-Benz',
        image: 'https://robohash.org/temporibusnecessitatibusvoluptatum.png?size=100x100&set=set1',
        added_date: '6/11/2019',
        rating: 3,
        price: 76.42,
        quantity: 56,
        status: false,
    },
    {
        id: 5,
        name: '626',
        category: 'Mazda',
        image: 'https://robohash.org/excepturirationedelectus.png?size=100x100&set=set1',
        added_date: '5/3/2019',
        rating: 4,
        price: 75.54,
        quantity: 337,
        status: false,
    },
    {
        id: 6,
        name: 'S-Class',
        category: 'Mercedes-Benz',
        image: 'https://robohash.org/autemrecusandaeut.png?size=100x100&set=set1',
        added_date: '8/10/2018',
        rating: 5,
        price: 340.36,
        quantity: 482,
        status: true,
    },
    {
        id: 7,
        name: 'Colt',
        category: 'Dodge',
        image: 'https://robohash.org/autaperiamaut.png?size=100x100&set=set1',
        added_date: '11/10/2018',
        rating: 5,
        price: 39.53,
        quantity: 436,
        status: false,
    },
    {
        id: 8,
        name: 'Yukon XL 2500',
        category: 'GMC',
        image: 'https://robohash.org/architectoetperspiciatis.png?size=100x100&set=set1',
        added_date: '7/9/2019',
        rating: 1,
        price: 126.56,
        quantity: 304,
        status: true,
    },
    {
        id: 9,
        name: 'F250',
        category: 'Ford',
        image: 'https://robohash.org/excepturivoluptassunt.png?size=100x100&set=set1',
        added_date: '9/23/2018',
        rating: 2,
        price: 354.81,
        quantity: 197,
        status: true,
    },
    {
        id: 10,
        name: 'GLC',
        category: 'Mazda',
        image: 'https://robohash.org/quodautaut.png?size=100x100&set=set1',
        added_date: '3/8/2019',
        rating: 4,
        price: 328.6,
        quantity: 472,
        status: true,
    }
];

const orders: Order[] = [
    {
        id: 1,
        order_id: '235',
        order_date: '17-Apr-2019',
        order_time: '7:56 PM',
        name_surname: 'Alberto Corini',
        cel: '069575656',
        order_code:'ORD-34567',
        address: 'Rome',
        order_status: 'Delivered',
    },
    {
        id: 2,
        order_id: '245',
        order_date: '17-Apr-2019',
        order_time: '7:56 PM',
        name_surname: 'Albi Corini',
        cel: '069575656',
        order_code:'ORD-34567',
        address: 'Rome',
        order_status: 'Processing',
    },
    {
        id: 3,
        order_id: '255',
        order_date: '17-Apr-2019',
        order_time: '7:56 PM',
        name_surname: 'Reando Corini',
        cel: '069575656',
        order_code:'ORD-34567',
        address: 'Rome',
        order_status: 'Shipped',
    },
];


export { products, orders};
